baseURL = 'https://www.raymondcao.dev/'
languageCode = 'en-us'
title = 'Raymond Cao'
theme = 'professional'

[params]
  description = 'Software Engineer & Tech Enthusiast'
  profile_picture = 'images/profile.jpg'
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/#about'
    weight = 10
  [[menu.main]]
    name = 'Experience'
    url = '/#experience'
    weight = 20
  [[menu.main]]
    name = 'Projects'
    url = '/#projects'
    weight = 30
  [[menu.main]]
    name = 'Posts'
    url = '/posts'
    weight = 40
  [[menu.main]]
    name = 'Contact'
    url = '/#contact'
    weight = 50
